#!/bin/bash

docker-compose -f docker-compose.yml down;
docker rm -v $(docker ps -a -q -f status=exited);
docker rmi $(docker images -f "dangling=true" -q);
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes;

exit 0;