FROM gulnap/kickoff-docker-php-images:toolbox-7.1.8-1

# |--------------------------------------------------------------------------
# | PHP extension for Redis
# |--------------------------------------------------------------------------
# |
# | Tells PHP to use Redis as the session handler.
# |

RUN { \
        echo 'session.save_handler=redis'; \
        echo 'session.save_path="tcp://redis:6379?auth={{ .EnvFiles.Kickoff.REDIS_PASSWORD }}"'; \
    } >> /usr/local/etc/php/conf.d/docker-php-ext-redis.ini

# |--------------------------------------------------------------------------
# | Permissions issues workaround
# |--------------------------------------------------------------------------
# |
# | On Linux, the UID arg will be set with the UID of the current user
# | from the host.
# |

ARG UID=1000
RUN usermod -u $UID www-data