#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

down()
{
    if [ -f ${ROOT}/docker-compose.yml ]; then
        if docker-compose -f ${ROOT}/docker-compose.yml down; then
            /bin/bash ${DIR}/misc/_whalesay --say "Apache (${APACHE_CONTAINER_NAME}) and MySQL (${MYSQL_CONTAINER_NAME}) containers have been stopped!";
        else
            /bin/bash ${DIR}/misc/_whalesay --say "Failed to stop the Apache (${APACHE_CONTAINER_NAME}) and MySQL (${MYSQL_CONTAINER_NAME}) containers.";
        fi;
    fi;
}

cache()
{
    docker rm $(docker ps -q -f status=exited) >/dev/null;
    docker rmi $(docker images -q -f dangling=true) >/dev/null
    docker volume rm $(docker volume ls -qf dangling=true) >/dev/null;
}

down;
cache;

exit 0;