#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

exportDatabase()
{
    /bin/bash ${DIR}/utils/_health_check --container_name ${MYSQL_CONTAINER_NAME};

    if [ $? -eq 1 ]; then
        /bin/bash ${DIR}/misc/_whalesay --say "MySQL container (${MYSQL_CONTAINER_NAME}) is not running.";
        exit 1;
    fi;

    if [ -f ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.sql ]; then
        rm -f ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.sql;
    fi;

    docker exec ${MYSQL_CONTAINER_NAME} mysqldump --opt -uroot -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} > ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.sql;
    cp ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.sql ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.$(date +%Y-%m-%d:%H:%M:%S).sql;

    /bin/bash ${DIR}/misc/_whalesay --say "Export task complete!";
}

exportDatabase;

exit 0;