#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

importDatabase()
{
    /bin/bash ${DIR}/utils/_health_check --container_name ${MYSQL_CONTAINER_NAME};

    if [ $? -eq 1 ]; then
        /bin/bash ${DIR}/misc/_whalesay --say "MySQL container (${MYSQL_CONTAINER_NAME}) is not running.";
        exit 1;
    fi;

    docker exec -i ${MYSQL_CONTAINER_NAME} mysql --verbose -uroot -p${MYSQL_ROOT_PASSWORD} -e "drop database $MYSQL_DATABASE";

    docker exec -i ${MYSQL_CONTAINER_NAME} mysql --verbose -uroot -p${MYSQL_ROOT_PASSWORD} -e "create database $MYSQL_DATABASE character set utf8 collate utf8_unicode_ci";

    cat ${ROOT}/mysql/dumps/${MYSQL_DATABASE}.sql | docker exec -i ${MYSQL_CONTAINER_NAME} mysql --verbose -uroot -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE};

    /bin/bash ${DIR}/misc/_whalesay --say "Import task complete!";
}

importDatabase;

exit 0;