#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

prepare()
{
    if [ -f ${ROOT}/docker-compose.yml ]; then
        rm -f ${ROOT}/docker-compose.yml;
    fi;

    cp ${ROOT}/docker-compose.yml.template ${ROOT}/docker-compose.yml;

    if [ -f ${ROOT}/docker-compose-reverse-proxy.yml ]; then
        rm -f ${ROOT}/docker-compose-reverse-proxy.yml;
    fi;

    cp ${ROOT}/docker-compose-reverse-proxy.yml.template ${ROOT}/docker-compose-reverse-proxy.yml;

    for f in ${DIR}/prepare/*; do
      if ! /bin/bash ${f}; then
        ${DIR}/misc/_whalesay --say "Failed to prepare your docker-compose files.";
        exit 1;
      fi;
    done;

    ${DIR}/misc/_whalesay --say "Your docker-compose files are ready!";
}

prepare;

exit 0;