#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

up()
{
    /bin/bash ${DIR}/utils/_health_check --container_name ${REVERSE_PROXY_CONTAINER_NAME};

    if [ $? -eq 1 ]; then
        if [ -f ${ROOT}/docker-compose-reverse-proxy.yml ]; then
            if docker-compose -p ${REVERSE_PROXY_NAME} -f docker-compose-reverse-proxy.yml up -d; then
                /bin/bash ${DIR}/misc/_whalesay --say "Reverse proxy container (${REVERSE_PROXY_CONTAINER_NAME}) is running!";
            else
                /bin/bash ${DIR}/misc/_whalesay --say "Failed to run the reverse proxy container (${REVERSE_PROXY_CONTAINER_NAME})";
                exit 1;
            fi;
        else
            /bin/bash ${DIR}/misc/_whalesay --say "No docker-compose-reverse-proxy.yml found. Did you run make prepare?";
            exit 1;
        fi;
    fi;
}

up;

exit 0;