#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/..;

# environment variables
source ${ROOT}/.env;

up()
{
    if [ -f ${ROOT}/docker-compose.yml ]; then
        if docker-compose -f ${ROOT}/docker-compose.yml up -d ; then
            /bin/bash ${DIR}/misc/_whalesay --say "Apache (${APACHE_CONTAINER_NAME}) and MySQL (${MYSQL_CONTAINER_NAME}) containers are running!";
        else
            /bin/bash ${DIR}/misc/_whalesay --say "Failed to up the Apache (${APACHE_CONTAINER_NAME}) and MySQL (${MYSQL_CONTAINER_NAME}) containers.";
            exit 1;
        fi;
    else
        /bin/bash ${DIR}/misc/_whalesay --say "No docker-compose.yml found. Did you run make prepare?";
        exit 1;
    fi;
}


up;

exit 0;