# |--------------------------------------------------------------------------
# | Down tasks
# |--------------------------------------------------------------------------
# |
# | This file describes the down tasks of your project.
# | Feel free to add your own tasks!
# |
# | https://github.com/gulien/orbit/
# |

tasks:

  # |--------------------------------------------------------------------------
  # | orbit run docker-sync-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops Docker Sync.
  # |

  - use: docker-sync-down
    run:
      {{ if eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC }}
      - docker-sync clean
      {{ else }}
      - echo Skipping Docker Sync shutdown ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run toolbox-down
  # |--------------------------------------------------------------------------
  # |
  # | Only useful to remove properly the backend network.
  # |

  - use: toolbox-down
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml down

  # |--------------------------------------------------------------------------
  # | orbit run traefik-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the Traefik container.
  # |
  # | It should be the last to stop.
  # |

  - use: traefik-down
    run:
      - docker-compose -p kickoff -f modules/traefik/docker-compose.yml down

  # |--------------------------------------------------------------------------
  # | orbit run graylog-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the Graylog containers.
  # |
  # | They should be stop before the Traefik container.
  # |

  - use: graylog-down
    run:
      {{ if eq true .Orbit.Modules.graylog.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/graylog/docker-compose.yml down
      {{ else }}
      - echo Skipping Graylog containers shutdown ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run php-fpm-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the PHP-FPM container.
  # |
  # | It should be stop before the Graylog containers.
  # |

  - use: php-fpm-down
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/php-fpm/docker-compose.yml down

  # |--------------------------------------------------------------------------
  # | orbit run nginx-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the NGINX container.
  # |
  # | It should be stop before the Graylog containers.
  # |

  - use: nginx-down
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/nginx/docker-compose.yml down

  # |--------------------------------------------------------------------------
  # | orbit run mysql-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the MySQL container.
  # |
  # | On "local" environment, also stops the phpMyAdmin container.
  # |
  # | They should be stop before the Graylog containers.
  # |

  - use: mysql-down
    run:
      {{ if eq true .Orbit.Modules.mysql.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/mysql/docker-compose.yml down
      {{ else }}
      - echo Skipping MySQL container shutdown ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run redis-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the Redis container.
  # |
  # | It should be stop before the Graylog containers.
  # |

  - use: redis-down
    run:
      {{ if eq true .Orbit.Modules.redis.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/redis/docker-compose.yml down
      {{ else }}
      - echo Skipping Redis container shutdown ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run rabbitmq-down
  # |--------------------------------------------------------------------------
  # |
  # | Stops the RabbitMQ container.
  # |
  # | It should be stop after the Graylog containers.
  # |

  - use: rabbitmq-down
    run:
      {{ if eq true .Orbit.Modules.rabbitmq.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/rabbitmq/docker-compose.yml down
      {{ else }}
      - echo Skipping RabbitMQ container shutdown ...
      {{ end }}