#!/bin/bash

usage()
{
    echo "Usage:";
    echo "./_health_check --container_name your_container_name";
    exit 0;
}

missing_arg()
{
    echo "ERROR: Missing argument $1."
    exit 1;
}

health_check()
{
    RUNNING=$(docker inspect --format="{{ .State.Running }}" ${CONTAINER_NAME} 2> /dev/null)

    if [ $? -eq 1 ] || [ "${RUNNING}" == "false" ]; then
        exit 1;
    fi;
}

# checking parameters
if [ "$#" -eq 0 ]; then
    usage;
    exit 1;
fi;

while [ "$1" != "" ]; do
    case $1 in
        --container_name ) shift
            if [ -z "$1" ]; then
                missing_arg --container_name;
            fi;
            CONTAINER_NAME=$1 ;;
    esac
    shift
done;

health_check;

exit 0;