#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
ROOT=${DIR}/../..;

# environment variables
source ${ROOT}/.env;

/bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_SERVICE_NAME}/${MYSQL_SERVICE_NAME}/g" ${ROOT}/docker-compose.yml;
/bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_CONTAINER_NAME}/${MYSQL_CONTAINER_NAME}/g" ${ROOT}/docker-compose.yml;
/bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_ROOT_PASSWORD}/${MYSQL_ROOT_PASSWORD}/g" ${ROOT}/docker-compose.yml;
/bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_DATABASE}/${MYSQL_DATABASE}/g" ${ROOT}/docker-compose.yml;

if [ ${MYSQL_ENABLE_PORTS_MAPPING} = 0 ]; then
    /bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_PORTS_MAPPING}/#\${MYSQL_PORTS_MAPPING}/g" ${ROOT}/docker-compose.yml;
    /bin/bash ${ROOT}/_bin/utils/_sedi "s/- \${MYSQL_HOST_PORT_TO_MAP}/#- \${MYSQL_HOST_PORT_TO_MAP}/g" ${ROOT}/docker-compose.yml;
else
    /bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_PORTS_MAPPING}/ports/g" ${ROOT}/docker-compose.yml;
    /bin/bash ${ROOT}/_bin/utils/_sedi "s/\${MYSQL_HOST_PORT_TO_MAP}/${MYSQL_HOST_PORT_TO_MAP}/g" ${ROOT}/docker-compose.yml;
fi;

exit 0;
